name: GlobalWarming
author: milkywayz 
main: net.porillo.GlobalWarming
version: ${project.version}
api-version: 1.13
commands:   
    globalwarming:
      aliases: gw
      description: The main command for GlobalWarming